os: linux
arch: s390x
dist: focal
language: c
services: docker
addons:
  hosts:
    - mariadb.example.com

cache:
  apt: true
  ccache: true
  directories:
    - $HOME/docker

env: local=0

jobs:
  fast_finish: true
  allow_failures:
    - env: srv=mariadb v=10.3 local=1    
  

script: ./travis.sh
